grails-app/domain/br/ufscar/tokenlab/Contact.groovy
package br.ufscar.tokenlab

class Contact {

    static belongsTo = [owner: User]

    String name
    Date birthday
    String email
    String address
    String phone


    static constraints = {
        name blank: false, nullable: false
        birthday nullable: false
        email blank: false, nullable: false
        address blank: false, nullable: false
        phone blank: false, nullable: false
    }
}

grails-app/domain/br/ufscar/tokenlab/Role.groovy
package br.ufscar.tokenlab

class Role {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}

grails-app/domain/br/ufscar/tokenlab/User.groovy
package br.ufscar.tokenlab
import br.ufscar.tokenlab.Contact

class User {

	static hasMany = [contacts: Contact]

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
		tablePerHierarchy false
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role }
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
}

grails-app/domain/br/ufscar/tokenlab/UserRole.groovy
package br.ufscar.tokenlab

import org.apache.commons.lang.builder.HashCodeBuilder

class UserRole implements Serializable {

	private static final long serialVersionUID = 1

	User user
	Role role

	boolean equals(other) {
		if (!(other instanceof UserRole)) {
			return false
		}

		other.user?.id == user?.id &&
		other.role?.id == role?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (user) builder.append(user.id)
		if (role) builder.append(role.id)
		builder.toHashCode()
	}

	static UserRole get(long userId, long roleId) {
		UserRole.where {
			user == User.load(userId) &&
			role == Role.load(roleId)
		}.get()
	}

	static boolean exists(long userId, long roleId) {
		UserRole.where {
			user == User.load(userId) &&
			role == Role.load(roleId)
		}.count() > 0
	}

	static UserRole create(User user, Role role, boolean flush = false) {
		def instance = new UserRole(user: user, role: role)
		instance.save(flush: flush, insert: true)
		instance
	}

	static boolean remove(User u, Role r, boolean flush = false) {
		if (u == null || r == null) return false

		int rowCount = UserRole.where {
			user == User.load(u.id) &&
			role == Role.load(r.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }

		rowCount > 0
	}

	static void removeAll(User u, boolean flush = false) {
		if (u == null) return

		UserRole.where {
			user == User.load(u.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }
	}

	static void removeAll(Role r, boolean flush = false) {
		if (r == null) return

		UserRole.where {
			role == Role.load(r.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }
	}

	static constraints = {
		role validator: { Role r, UserRole ur ->
			if (ur.user == null) return
			boolean existing = false
			UserRole.withNewSession {
				existing = UserRole.exists(ur.user.id, r.id)
			}
			if (existing) {
				return 'userRole.exists'
			}
		}
	}

	static mapping = {
		id composite: ['role', 'user']
		version false
	}
}

grails-app/controllers/br/ufscar/tokenlab/ContactController.groovy
package br.ufscar.tokenlab

import grails.plugin.springsecurity.annotation.Secured

import java.security.Security

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured('IS_AUTHENTICATED_FULLY')
class ContactController {
    def springSecurityService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index() {
        def user = springSecurityService.getCurrentUser()
        def list = Contact.findAllByOwner(user)
        respond list, model:[contactInstanceCount: list.size()]
    }

    def show(Contact contactInstance) {
        respond contactInstance
    }

    def create() {
        respond new Contact(params)
    }

    @Transactional
    def save(Contact contactInstance) {
        if (contactInstance == null) {
            notFound()
            return
        }

        String place = params.place
        String zipcode = params.zipcode
        String neighborhood = params.neighborhood
        String complement = params.complement
        String number = params.number
        String city = params.city
        String state = params.state

        contactInstance.address = place + ", " + number + " - " + neighborhood + " - " + complement + " - " + city + "-" + state + " - " + zipcode

        contactInstance.owner = springSecurityService.getCurrentUser()

        contactInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'contact.label', default: 'Contact'), contactInstance.id])
                redirect contactInstance
            }
            '*' { respond contactInstance, [status: CREATED] }
        }
    }

    def edit(Contact contactInstance) {
        respond contactInstance
    }

    @Transactional
    def update(Contact contactInstance) {
        if (contactInstance == null) {
            notFound()
            return
        }

        if (contactInstance.hasErrors()) {
            respond contactInstance.errors, view:'edit'
            return
        }

        contactInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Contact.label', default: 'Contact'), contactInstance.id])
                redirect contactInstance
            }
            '*'{ respond contactInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Contact contactInstance) {

        if (contactInstance == null) {
            notFound()
            return
        }

        contactInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Contact.label', default: 'Contact'), contactInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'contact.label', default: 'Contact'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/contact/_form.gsp
<%@ page import="br.ufscar.tokenlab.Contact" %>



<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="contact.name.label" default="Nome" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${contactInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'birthday', 'error')} required">
	<label for="birthday">
		<g:message code="contact.birthday.label" default="Data de aniversário" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="birthday" precision="day"  value="${contactInstance?.birthday}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="contact.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="email" required="" value="${contactInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'address', 'error')} required">
	<label for="address">
		<g:message code="contact.address.label" default="Endereço" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="address" required="" value="${contactInstance?.address}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'phone', 'error')} required">
	<label for="phone">
		<g:message code="contact.phone.label" default="Telefone" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="phone" required="" value="${contactInstance?.phone}"/>

</div>

grails-app/views/contact/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'contact.label', default: 'Contato')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-contact" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-contact" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${contactInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${contactInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:contactInstance, action:'save']" >
				<fieldset class="form">
					<%@ page import="br.ufscar.tokenlab.Contact" %>



					<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'name', 'error')} required">
						<label for="name">
							<g:message code="contact.name.label" default="Nome" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField name="name" required="" value="${contactInstance?.name}"/>

					</div>

					<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'birthday', 'error')} required">
						<label for="birthday">
							<g:message code="contact.birthday.label" default="Data de aniversário" />
							<span class="required-indicator">*</span>
						</label>
						<g:datePicker name="birthday" precision="day"  value="${contactInstance?.birthday}"  />

					</div>

					<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'email', 'error')} required">
						<label for="email">
							<g:message code="contact.email.label" default="Email" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField name="email" required="" value="${contactInstance?.email}"/>

					</div>

					<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'phone', 'error')} required">
						<label for="phone">
							<g:message code="contact.phone.label" default="Telefone" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField name="phone" required="" value="${contactInstance?.phone}"/>

					</div>


					<div class="fieldcontain required">
						<label for="zipcode">
							<g:message code="contact.zipcode.label" default="Cep" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField id="zipcode" onblur="" name="zipcode" required="" value="${}"/>
					</div>

					<div class="fieldcontain required">
						<label for="place">
							<g:message code="contact.place.label" default="Logradouro" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField id="place"  name="place" required="" />
					</div>

					<div class="fieldcontain required">
						<label for="number">
							<g:message code="contact.numer.label" default="Número" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField id="number" name="number" required="" />
					</div>

					<div class="fieldcontain ">
						<label for="complement">
							<g:message code="contact.complement.label" default="Complemento" />
						</label>
						<g:textField id="complement" name="complement" />
					</div>

					<div class="fieldcontain required">
						<label for="neighborhood">
							<g:message code="contact.neighborhood.label" default="Bairro" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField id="neighborhood" name="neighborhood" required=""/>
					</div>

					<div class="fieldcontain required">
						<label for="city">
							<g:message code="contact.city.label" default="Cidade" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField id="city" name="city" required="" />
					</div>

					<div class="fieldcontain required">
						<label for="state">
							<g:message code="contact.state.label" default="Estado" />
							<span class="required-indicator">*</span>
						</label>
						<g:textField id="state" name="state" required="" />
					</div>

					<input type="hidden" id="address" name="address" value="address" />

				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>

	<script type="text/javascript" >

		$(document).ready(function() {
			$("#zipcode").blur(function() {
				var zipcode = $(this).val();
				$.getJSON("//viacep.com.br/ws/" + zipcode + "/json/?callback=?", function (data) {
					if (!("erro" in data)) {
						$("#place").val(data.logradouro);
						$("#neighborhood").val(data.bairro);
						$("#city").val(data.localidade);
						$("#state").val(data.uf);
					}
					else {
						alert("CEP não encontrado.");
					}
				});
			});
		});
	</script>
	</body>
</html>

grails-app/views/contact/edit.gsp
<%@ page import="br.ufscar.tokenlab.Contact" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'contact.label', default: 'Contato')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-contact" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-contact" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${contactInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${contactInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:contactInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${contactInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/contact/index.gsp
<%@ page import="br.ufscar.tokenlab.Contact" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<title>Agenda de Contatos</title>
	</head>
	<body>
		<a href="#list-contact" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}">Página inicial</a></li>
				<li><g:link class="create" action="create">Criar novo contato</g:link></li>
			</ul>
		</div>
		<div id="list-contact" class="content scaffold-list" role="main">
			<h1>Agenda de Contatos</h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="name" title="${message(code: 'contact.name.label', default: 'Nome')}" />
						<g:sortableColumn property="birthday" title="${message(code: 'contact.birthday.label', default: 'Data de Aniversário')}" />
						<g:sortableColumn property="email" title="${message(code: 'contact.email.label', default: 'Email')}" />
						<g:sortableColumn property="address" title="${message(code: 'contact.address.label', default: 'Endereço')}" />
						<g:sortableColumn property="phone" title="${message(code: 'contact.phone.label', default: 'Telefone')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${contactInstanceList}" status="i" var="contactInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${contactInstance.id}">${fieldValue(bean: contactInstance, field: "name")}</g:link></td>
						<td><g:formatDate format="dd/MM/yyyy" date="${contactInstance.birthday}" /></td>
						<td>${fieldValue(bean: contactInstance, field: "email")}</td>
						<td>${fieldValue(bean: contactInstance, field: "address")}</td>
						<td>${fieldValue(bean: contactInstance, field: "phone")}</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${contactInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/contact/show.gsp
<%@ page import="br.ufscar.tokenlab.Contact" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'contact.label', default: 'Contato')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-contact" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-contact" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list contact">
			
				<g:if test="${contactInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="contact.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${contactInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.birthday}">
				<li class="fieldcontain">
					<span id="birthday-label" class="property-label"><g:message code="contact.birthday.label" default="Birthday" /></span>
					
						<span class="property-value" aria-labelledby="birthday-label"><g:formatDate format="dd/MM/yyyy" date="${contactInstance?.birthday}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.email}">
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="contact.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${contactInstance}" field="email"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.address}">
				<li class="fieldcontain">
					<span id="address-label" class="property-label"><g:message code="contact.address.label" default="Address" /></span>
					
						<span class="property-value" aria-labelledby="address-label"><g:fieldValue bean="${contactInstance}" field="address"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.phone}">
				<li class="fieldcontain">
					<span id="phone-label" class="property-label"><g:message code="contact.phone.label" default="Phone" /></span>
					
						<span class="property-value" aria-labelledby="phone-label"><g:fieldValue bean="${contactInstance}" field="phone"/></span>
					
				</li>
				</g:if>
			

			</ol>
			<g:form url="[resource:contactInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${contactInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><g:layoutTitle default="Grails"/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
    <link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
    <asset:stylesheet src="application.css"/>
    <asset:javascript src="application.js"/>
    <g:layoutHead/>
</head>
<body>
<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
<g:layoutBody/>
<div class="footer" role="contentinfo"></div>
<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
</body>
</html>